// resources/js/components/TopNav.vue
<template>
    <div class="flex justify-between items-center px-6 p-3 bg-gray-800 w-full md:w-5/6 fixed right-0 top-0 text-gray-200 z-10">
        <p class="font-bold">name</p>
        <button class="md:hidden">menu</button>
        <button class="hidden md:block">logout</button>
    </div>
</template>

// app/components/TopNav.tsx
'use client'

import { SignOut } from "../utils/SignOut"

export default function TopNav() {

    const handleLogout = async () => {
        await SignOut()
    }

    return (
        <div className="fixed top-0 right-0 w-full md:w-5/6 bg-zinc-600 z-10 flex justify-between items-center p-2">
            <header>
                <h1 className="text-2xl text-white">Clinic Mangement</h1>
            </header>
            <button onClick={handleLogout} type="button" className="">logout</button>
        </div>
    )
}
