// app/admin/scheduling/create/page.tsx
'use client'

import axios from "axios";
import Link from "next/link";
import { ChangeEvent, FormEvent, useCallback, useEffect, useState } from "react"
import { ToastContainer, toast } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import Swal from "sweetalert2";
interface Patient {
    _id: string;
    first_name: string;
    middle_name: string;
    last_name: string;
    extension?: string; 
}

export default function Create() {
    const [scheduleForm, setScheduleForm] = useState<{
        patient: string;
        schedule: Date;
        consultation_type: string;
    }>({
        patient: '',
        schedule: new Date(),
        consultation_type: 'consultation',
    })
    const [patients, setPatients] = useState<Patient[]>([])

    const getPatients = useCallback(async () => {
        await axios.get('/api/patient')
            .then(response => {
                const p = response.data?.patient
                setPatients(p)
            })
            .catch(error => {
                console.log(error)
                toast.error('Error')
            })
    }, [])

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault()
        await axios.post('/api/schedule/admin', scheduleForm)
        .then(() => {
            setScheduleForm({
                patient: '',
                schedule: new Date(),
                consultation_type: 'consultation',
            })
            toast.success('Success')
        })
        .catch(error => {
            console.log(error)
            Swal.fire({
                title: 'Error',
                text: error.response?.data?.message
            })
        })
    }
    
    useEffect(() => {
        getPatients()
    }, [getPatients])

    const handleOnChange = (e: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        const { name, value } = e.target
        setScheduleForm({
            ...scheduleForm,
            [name]: value
        })
    }

    return(
        <div className="w-full flex justify-center items-center">
            <ToastContainer position="bottom-right" />
            <section className="w-full md:w-[550px] rounded-lg shadow-xl p-5 bg-zinc-400">
                <header className="mb-5 font-semibold flex justify-start items-center gap-2">
                    <Link href={'/admin/scheduling'} className="p-2 rounded text-white text-sm font-bold bg-blue-600 hover:bg-blue-900">back</Link>
                    <h1 className="text-2xl">Create Appointment</h1>
                </header>
                <form onSubmit={handleSubmit}>
                    <div className="w-full space-y-2">
                        <div className="w-full group">
                            <label htmlFor="patient" className="text-xs font-bold">Patient:</label>
                            <select 
                                className="w-full p-2 rounded"
                                name="patient" 
                                id="patient"
                                value={scheduleForm.patient}
                                onChange={handleOnChange}
                            >
                                <option value="">--select--</option>
                                {
                                    patients.map((patient,index) => {
                                        return(
                                            <option key={index} value={patient._id}>
                                                {patient.first_name} {patient.middle_name} {patient.last_name} {patient.extension}
                                            </option>
                                        )
                                    })
                                }
                            </select>
                        </div>
                        <div className="w-full group">
                            <label htmlFor="schedule" className="text-xs font-bold">Schedule:</label>
                            <input 
                                type="datetime-local" 
                                name="schedule" 
                                id="schedule" 
                                className="w-full p-2 rounded" 
                                value={scheduleForm.schedule ? new Date(scheduleForm.schedule).toISOString().substring(0, 10) : ''}
                                onChange={handleOnChange}
                            />
                        </div>
                        <div className="w-full group">
                            <label htmlFor="consultation_type" className="text-xs font-bold">Consultation Type:</label>
                            {/* <input 
                                type="text" 
                                name="consultation_type" 
                                id="consultation_type" 
                                className="w-full p-2 rounded" 
                                value={scheduleForm.consultation_type}
                                onChange={handleOnChange}
                            /> */}
                            <select 
                                name="consultation_type" 
                                id="consultation_type"
                                className="w-full p-2 rounded" 
                                value={scheduleForm.consultation_type}
                                onChange={handleOnChange}
                            >
                                <option value="consultation">Consultation</option>
                                <option value="medical-examination">Medical Examination</option>
                                <option value="dental-consultation">Dental Consultation</option>
                            </select>
                        </div>
                        <button className="p-2 rounded text-white text-xs font-bold bg-indigo-600 hover:bg-indigo-900">
                            submit
                        </button>
                    </div>
                </form>
            </section>
        </div>
    )
}

// resources/js/pages/patient/Create.vue
<template>
    <div class="flex justify-center items-center w-full min-h-screen">
        <section class="w-96 md:w-3/5 p-10 rounded-lg shadow-xl bg-gray-900 mt-20">
            <h1 class="text-2xl text-gray-400 mb-5">Patient Information</h1>
            <div class="flex flex-col md:flex-row gap-4 text-gray-200 mb-4">
                <div class="group rounded p-3 ring-2 ring-gray-400 focus-within:ring-indigo-600 w-full md:w-1/2">
                    <label for="first_name" class="text-xs font-bold w-full">First name:</label>
                    <input 
                        type="text" 
                        name="first_name" 
                        id="first_name" 
                        v-model="this.first_name"
                        class="w-full rounded bg-gray-900 outline-none p-2" 
                        placeholder="First name"
                    />
                </div>
                <div class="group rounded p-3 ring-2 ring-gray-400 focus-within:ring-indigo-600 w-full md:w-1/2">
                    <label for="last_name" class="text-xs font-bold">Last name:</label>
                    <input 
                        type="text" 
                        name="last_name" 
                        id="last_name" 
                        v-model="this.last_name"
                        class="w-full rounded bg-gray-900 outline-none p-2" 
                        placeholder="Last name"
                    />
                </div>
            </div>
            <div class="flex flex-col md:flex-row gap-4 text-gray-200 mb-4">
                <div class="group rounded p-3 ring-2 ring-gray-400 focus-within:ring-indigo-600 w-full md:w-1/3">
                    <label for="date_of_birth" class="text-xs font-bold">Date of birth:</label>
                    <input 
                        type="date" 
                        name="date_of_birth" 
                        v-model="this.date_of_birth"
                        id="date_of_birth" 
                        class="w-full rounded bg-gray-900 outline-none p-2" 
                    />
                </div>
                <div class="group rounded p-3 ring-2 ring-gray-400 focus-within:ring-indigo-600 w-full md:w-1/3">
                    <label for="employment_status" class="text-xs font-bold">Employment Status:</label>
                    <select v-model="this.employment_status" name="employment_status" id="employment_status" class="w-full rounded bg-gray-900 outline-none p-2" >
                        <option value="student">Student</option>
                        <option value="employee">Employee</option>
                    </select>
                </div>
                <div class="group rounded p-3 ring-2 ring-gray-400 focus-within:ring-indigo-600 w-full md:w-1/3">
                    <label for="id_number" class="text-xs font-bold">ID number:</label>
                    <input 
                        type="text" 
                        name="id_number" 
                        id="id_number" 
                        v-model="this.id_number" 
                        :readonly="this.is_id_num_null"
                        class="w-full rounded bg-gray-900 outline-none p-2" 
                    />
                </div>
            </div>
            <button @click="createPatient" class="w-full md:w-1/2 p-3 rounded bg-indigo-600 hover:bg-indigo-500">Create</button>
        </section>
    </div>
</template>

<script>
    import axios from 'axios';
import Swal from 'sweetalert2';
    export default {
        data() {
            return {
                first_name: '',
                last_name: '',
                date_of_birth: '',
                employment_status: 'student',
                id_number: '',
                is_id_num_null: false
            }
        },
        created() {
            this.setIdNumber()
        },
        watch: {
            '$route.params.id_number': function(newId) {
                this.id_number = newId
                this.is_id_num_null = newId != null ? true : false
            }
        },
        methods: {
            setIdNumber() {
                const r = this.$route.params.id_number
                this.id_number = this.$route.params.id_number
                this.is_id_num_null = (r == null || r == '' ? false : true)
            },
            createPatient() {
                axios.post('/api/patient/store', {
                    id_number: this.id_number,
                    first_name: this.first_name,
                    last_name: this.last_name,
                    date_of_birth: this.date_of_birth,
                    employment_status: this.employment_status,
                })
                .then(response => {
                    Swal.fire({
                        title: 'Success',
                        text: response.data.message,
                        icon: 'success',
                        showConfirmButton: true,
                    })
                    this.$router.push(`/assessment/create/${response.data?.patient?.id_number}`)
                })
                .catch(error => {
                    console.log(error)
                })
            }
        }
    }
</script>
